import { getDatabaseProvider } from "./provider";
import * as sqliteApp from "./app.schema";
import * as sqliteCandidateKeywords from "./candidate-keywords.schema";
import * as sqliteContentFactory from "./content-factory.schema";
import * as sqliteContentOps from "./content-ops.schema";
import * as sqliteOpportunityIntel from "./opportunity-intel.schema";
import * as sqliteProjectContext from "./project-context.schema";
import * as sqliteProjectSites from "./project-sites.schema";
import * as sqliteReports from "./reports.schema";
import * as sqliteReportTemplates from "./report-templates.schema";
import * as sqliteAudit from "./audit.schema";
import * as sqliteSam from "./sam.schema";
import * as sqliteAuth from "./better-auth-schema";
import * as sqliteBilling from "./billing.schema";
import * as sqliteGa4 from "./ga4.schema";
import * as sqliteGsc from "./gsc.schema";
import * as sqliteTelemetry from "./telemetry.schema";
import * as pgApp from "./pg/app.schema";
import * as pgCandidateKeywords from "./pg/candidate-keywords.schema";
import * as pgContentFactory from "./pg/content-factory.schema";
import * as pgContentOps from "./pg/content-ops.schema";
import * as pgOpportunityIntel from "./pg/opportunity-intel.schema";
import * as pgProjectContext from "./pg/project-context.schema";
import * as pgProjectSites from "./pg/project-sites.schema";
import * as pgReports from "./pg/reports.schema";
import * as pgReportTemplates from "./pg/report-templates.schema";
import * as pgAudit from "./pg/audit.schema";
import * as pgSam from "./pg/sam.schema";
import * as pgAuth from "./pg/better-auth-schema";
import * as pgBilling from "./pg/billing.schema";
import * as pgGa4 from "./pg/ga4.schema";
import * as pgGsc from "./pg/gsc.schema";
import * as pgTelemetry from "./pg/telemetry.schema";

// Canonical schema barrel. Repositories import their tables from here and the
// provider-aware `db` from "@/db", so each repository is written ONCE for both
// backends.
//
// The TYPE identity is the SQLite definitions; the runtime VALUES are whichever
// provider is active. `schema-parity.test.ts` asserts the two dialect schemas
// are structurally interchangeable (same tables/columns/nullability/PKs/unique
// indexes), which is what makes the single cast below sound. The Postgres
// schema is the one structural artifact NOT regenerated by `db:generate`, so the
// parity test is its drift guard.
type AppSchema = typeof sqliteApp &
  typeof sqliteCandidateKeywords &
  typeof sqliteContentFactory &
  typeof sqliteContentOps &
  typeof sqliteOpportunityIntel &
  typeof sqliteProjectContext &
  typeof sqliteProjectSites &
  typeof sqliteReports &
  typeof sqliteReportTemplates &
  typeof sqliteAudit &
  typeof sqliteSam &
  typeof sqliteAuth &
  typeof sqliteBilling &
  typeof sqliteGa4 &
  typeof sqliteGsc &
  typeof sqliteTelemetry;

const runtimeSchema =
  getDatabaseProvider() === "postgres"
    ? {
        ...pgApp,
        ...pgCandidateKeywords,
        ...pgContentFactory,
        ...pgContentOps,
        ...pgOpportunityIntel,
        ...pgProjectContext,
        ...pgProjectSites,
        ...pgReports,
        ...pgReportTemplates,
        ...pgAudit,
        ...pgSam,
        ...pgAuth,
        ...pgBilling,
        ...pgGa4,
        ...pgGsc,
        ...pgTelemetry,
      }
    : {
        ...sqliteApp,
        ...sqliteCandidateKeywords,
        ...sqliteContentFactory,
        ...sqliteContentOps,
        ...sqliteOpportunityIntel,
        ...sqliteProjectContext,
        ...sqliteProjectSites,
        ...sqliteReports,
        ...sqliteReportTemplates,
        ...sqliteAudit,
        ...sqliteSam,
        ...sqliteAuth,
        ...sqliteBilling,
        ...sqliteGa4,
        ...sqliteGsc,
        ...sqliteTelemetry,
      };

// oxlint-disable-next-line typescript/no-unsafe-type-assertion -- guarded by schema-parity.test.ts
const schema = runtimeSchema as unknown as AppSchema;

export const {
  userOnboardingAnswers,
  projects,
  savedKeywords,
  savedKeywordTags,
  savedKeywordTagAssignments,
  keywordMetrics,
  candidateKeywords,
  offers,
  clusters,
  clusterKeywords,
  serpSnapshots,
  serpResults,
  deploymentDecisions,
  decisionLog,
  evidencePacks,
  contentAssets,
  contentBudgets,
  researchPages,
  knowledgeEntries,
  knowledgeSources,
  knowledgeUsages,
  knowledgeDeltas,
  knowledgeConflicts,
  opportunities,
  opportunityRelationships,
  opportunityKeywords,
  opportunitySerpSnapshots,
  opportunitySerpResults,
  opportunityScores,
  opportunityDecisionLog,
  opportunityRuns,
  opportunityReports,
  opportunityCostEvents,
  opportunityBudgets,
  rankTrackingConfigs,
  rankTrackingKeywords,
  rankCheckRuns,
  rankSnapshots,
  organizationActivationState,
  projectActivationState,
  dashboardStepDismissals,
  backlinkSnapshots,
  projectContextSections,
  projectCompetitors,
  projectKeyPages,
  projectResearchLog,
  projectSites,
  projectMarkets,
  reports,
  reportTemplates,
  audits,
  auditPages,
  auditIssues,
  auditLighthouseResults,
  samSessions,
  user,
  session,
  account,
  apikey,
  verification,
  organization,
  member,
  invitation,
  billingCustomerStatus,
  ga4Connections,
  gscConnections,
  telemetryState,
} = schema;
